### ISSUE TITLE
'npm run format-js' fails

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/community-theme-default#3]
It's a bit difficult to find out on how to re-build the theme as-is. Couldn't find any documentation for it, neither for PS 1.6. Plan is to tweak the default theme with a set of commits, in order to ease upgrading later and to not miss future changes.

Looking at the code, I assume it goes like this:
```sh
cd themes/community-theme-default
npm install  # and wait a minute
npm run compile-css
npm run format-js
```

The last of these commands fails:
```sh
$ npm run format-js

> community-theme-default@ format-js /var/www/html/ThirtyBees/themes/community-theme-default
> gulp format-js

[15:42:25] Using gulpfile /var/www/html/ThirtyBees/themes/community-theme-default/gulpfile.js
[15:42:25] Starting 'format-js'...
[15:42:25] 'format-js' errored after 68 ms
[15:42:25] TypeError: Cannot set property 'maxErrors' of undefined
    at module.exports (/var/www/html/ThirtyBees/themes/community-theme-default/node_modules/gulp-jscs/index.js:31:20)
    at Gulp.<anonymous> (/var/www/html/ThirtyBees/themes/community-theme-default/gulpfile.js:122:9)
    at module.exports (/var/www/html/ThirtyBees/themes/community-theme-default/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/html/ThirtyBees/themes/community-theme-default/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/html/ThirtyBees/themes/community-theme-default/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/html/ThirtyBees/themes/community-theme-default/node_modules/orchestrator/index.js:134:8)
    at /var/www/html/ThirtyBees/themes/community-theme-default/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
    at Function.Module.runMain (module.js:443:11)

npm ERR! Linux 4.10.0-041000-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "format-js"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! community-theme-default@ format-js: `gulp format-js`
npm ERR! Exit status 1
[...]
```

**Comment by Dh42** [comment]
Can you pull from the 1.o.x branch and try now.

**Comment by Traumflug** [comment]
Yes, works fine now:

```sh
$ npm run format-js

> community-theme-default@ format-js /var/www/html/ThirtyBees/themes/community-theme-default
> gulp format-js

[15:08:03] Using gulpfile /var/www/html/ThirtyBees/themes/community-theme-default/gulpfile.js
[15:08:03] Starting 'format-js'...
[15:08:05] Finished 'format-js' after 1.65 s
```

Thank you for fixing this!
